import { useState } from 'react';
import { Search, ChevronRight } from 'lucide-react';

// NOTE: Article/thumbnail images below are temporary placeholder URLs
// generated by the Stitch design tool (googleusercontent.com). Swap these
// for your own blog images in src/assets when ready.

const articles = [
  {
    id: 'web-dev-trends-2024',
    title: 'The Future of Web Development: Trends to Watch in 2024',
    excerpt:
      'Discover the latest trends in web development that will shape the future, from AI-driven coding to advanced frameworks.',
    date: 'May 15, 2024',
    readTime: '5 min read',
    category: 'Web Development',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuD5HDaJPlR0AAHXNoQLx_QLhg-YM2zWZVUy0kKl_D6CsKgRAbOjA4ru0meeCjvsaa6rB-f1oRM5drPzMYEbuCz8ayXrjvxd9qT6zd__Ia5yLye7TxgvorrKvb0GIvLc6hXAOuHC6fu2l2t2O8xZsr4HNBae2lP6VaNoa-5-O-jArdTG-aag1HJq7Om3rawVi-lEDOAd_iGVIrvZpX8dePqJSozzDITdPvtuJu9uJq2wx0WLigD5LXYzPA',
  },
  {
    id: 'blockchain-transforming-business',
    title: 'How Blockchain is Transforming Businesses',
    excerpt:
      'Explore how blockchain technology is revolutionizing industries across the world with decentralization.',
    date: 'May 05, 2024',
    readTime: '6 min read',
    category: 'Blockchain',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuALCaWwWleGoeuIcaLXvasK9J5_cy-HtKrTA9wBErmTY3Idm-bsoEWLBSP_cA6OplQBwl-tqtRG7oHu2pwfMkkoWWfgvdqFLTVnb5bUDg-_hDMa5eyVAod58fN4p10QvLXhs1ovc6_ORtw84M_ja5JxWVGwjNFmYl0IudohJIBUzg0wDvJqUSV2QfAWm5rwxVtvfacBpYD7eabGh5wTj5rcRVwqHXkfXRJGR3tZ2c1MAN_FeHtMJ19bYQ',
  },
  {
    id: 'crm-benefits-small-business',
    title: 'Top 10 Benefits of CRM for Small Businesses',
    excerpt:
      'Learn how CRM systems can help small businesses improve efficiency, customer relations and grow faster.',
    date: 'Apr 28, 2024',
    readTime: '4 min read',
    category: 'CRM',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAEh2MSxkEPwJffQ0A88Y-5YRplrC8sQTZRSuGwlH462JF8IhL1RvfOC_PBwCUSkC0ijAffeNtJ0__Aq0fZ2UziQ1-PhSnBUmoDpC__3BjNgoH2XCxpoZELhsriiRNe23WJoaanT2yhvs89D-QTZvvnIrt1zl38Zhf39Hqxa4UZqmjz2RjxON0o9k0UF_lI7YZP5CC8qV6oTp3ZopLWf2XoDEUxSqDPmNDDNuEosfydySuk2MLvMkRdYA',
  },
  {
    id: 'ai-automation-business-growth',
    title: 'AI & Automation: The Key to Business Growth',
    excerpt:
      'Understand how AI and automation can optimize operations and drive sustainable business growth.',
    date: 'Apr 20, 2024',
    readTime: '5 min read',
    category: 'AI & Automation',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuD-Mno3HYqfssWJoAq_PiDPFXpMKRkGrGrBiVGk7CQiTk2HrgWIbg28zbcyajKM7vCd1-oKHj3WnRiUx6vFCiD5xtfD_ps2CQ58ds8lpjr2UnvAav_VB7EY6NaN3k7P7uYbCXJKd8ZUnS43qe8KhD3rxqsVTqULW1hTAcTzkkQsd81A8gWHiHFnzDyBEKgNkvkT6u--yw5KoRzG2LLA3LPWMn6NJvDBVwBVwT9PEClQbJqJrsJftxoAmA',
  },
];

const categories = [
  'All Articles',
  'Web Development',
  'Blockchain',
  'Mobile Apps',
  'CRM',
  'Digital Marketing',
  'AI & Automation',
];

const popularPosts = [
  {
    id: 'popular-web-dev',
    title: 'The Future of Web Development',
    date: 'May 15, 2024',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCYOI2-24uwGMjzKGI0PTTmRBSSOZ9QkT5cdGJ9JR6obSL6o2Q1gXwgwkdgIDkIdRtaO1iCZDil7vwKFavyktRxjuqHWFi8YxJKMK81s87Lgx_tipAMeYQkjPYvXsE31ujGExWxiouELlLYZ0n4OnRGSLYucing1tv2fxPxlHA-zbFv4v2r1aY0gvs1CzS0m3_cZhM3qBorOZE8ATMzkpfHD9NzOi-w_nFedCBxOjRpOnHjpET3XdovQQ',
  },
  {
    id: 'popular-blockchain',
    title: 'How Blockchain is Transforming Businesses',
    date: 'May 05, 2024',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBk18qlaxO43w6M4HXGxC6w_dx_6t8-AmLgHC5WJmD67vR0MZum3J1q8iXNLBi-6fkQ-uJ4hgJ1A8GbBEDiNvodf19hMdTJxpc8G7LeuD83P94L--2YzviUmWcpsKN_YqFzf24wffzovEjKm0hS0cNHfgZGEGiKvqeWfBIATD4orFoo1YxCuyYuCdI-8AfPqTAHErWqTVlLejLCYoi1JYrajaF2kdZQldYWQiOwXqMs96IcokFXhcMUrA',
  },
  {
    id: 'popular-crm',
    title: 'Top 10 Benefits of CRM for Small Businesses',
    date: 'Apr 28, 2024',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAony0T9bTDKd3mnb25BGfeXUk0DRHMwXsUlaOdeKb-A1WYWK_JBlChHcI3_gX301pJxKrHOnw5V3ONkLVhbDCKjsZzx7t8C0VfUBvVKMxsUyyqghx5V1CDfsWpIrPHv2Nz8fUP3xHmbtkHdSben9Q31ZnScWe6SxmtmpXUlGjaWd6U6GvRmp8SZDqSDNwxdSssangAW2Jk0BnBpfPuPSEybopwlUa0nR8WHoQlgCXiw5CSkXDXATAE1g',
  },
];

function Blog() {
  const [activeCategory, setActiveCategory] = useState('All Articles');
  const [searchQuery, setSearchQuery] = useState('');

  const filteredArticles = articles.filter((article) => {
    const matchesCategory =
      activeCategory === 'All Articles' || article.category === activeCategory;
    const matchesSearch = article.title
      .toLowerCase()
      .includes(searchQuery.trim().toLowerCase());
    return matchesCategory && matchesSearch;
  });

  return (
    <main className="relative min-h-screen bg-[#faf8ff] tech-grid overflow-x-hidden">
      {/* Atmospheric Glows */}
      <div className="floating-radial bg-[#003594] top-0 -left-64" />
      <div className="floating-radial bg-[#006c49] bottom-0 -right-64" />

      <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-0 pb-12 md:py-20">
        {/* Header Section */}
        <header className="flex flex-col lg:flex-row lg:items-end justify-between  mb-16 gap-8">
          <div className="max-w-3xl">
            <span className="font-['Hanken_Grotesk'] text-[#003594] text-lg leading-4 tracking-[0.3em] font-bold uppercase mb-3 block">
              Our Blog
            </span>
            <h1 className="font-['Hanken_Grotesk'] text-4xl md:text-[54px] leading-tight md:leading-[64px] font-black tracking-tight text-[#131b2e] mb-4">
              Insights, Ideas &amp; <br className="hidden md:block" />
              Industry <span className="gradient-text">Trends</span>
            </h1>
            <p className="text-[#434654] text-lg md:text-xl leading-relaxed max-w-2xl font-normal">
              Stay updated with the latest insights, tips, and trends in technology and digital
              transformation.
            </p>
          </div>

          {/* Search Bar */}
          <div className="w-full lg:max-w-xs">
            <div className="relative group">
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search articles..."
                className="w-full pl-4 pr-12 py-3.5 bg-white border border-[#c3c6d6]/30 rounded-xl focus:ring-2 focus:ring-[#003594] focus:border-transparent outline-none transition-all duration-300 shadow-sm group-hover:shadow-md text-[#131b2e]"
              />
              <Search className="absolute right-4 top-1/2 -translate-y-1/2 h-5 w-5 text-[#737685] pointer-events-none" />
            </div>
          </div>
        </header>

        {/* Main Content Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-16">
          {/* Articles List */}
          <section className="lg:col-span-8 space-y-10">
            {filteredArticles.length === 0 && (
              <p className="text-[#434654] text-base">
                No articles found{activeCategory !== 'All Articles' ? ` in "${activeCategory}"` : ''}
                {searchQuery ? ` matching "${searchQuery}"` : ''}.
              </p>
            )}
            {filteredArticles.map((article) => (
              <article
                key={article.id}
                className="group flex flex-col md:flex-row gap-6 p-2 -m-2 rounded-2xl hover:bg-white transition-all duration-300 cursor-pointer"
              >
                <div className="w-full md:w-64 h-44 flex-shrink-0 overflow-hidden rounded-2xl bg-[#eaedff]">
                  <img
                    src={article.image}
                    alt={article.title}
                    className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-110"
                  />
                </div>
                <div className="flex flex-col justify-center py-2">
                  <h2 className="text-[22px] leading-tight font-bold text-[#131b2e] mb-3 group-hover:text-[#003594] transition-colors duration-300">
                    {article.title}
                  </h2>
                  <p className="text-[#434654] text-base leading-relaxed mb-4 line-clamp-2">
                    {article.excerpt}
                  </p>
                  <div className="flex items-center gap-3 font-['JetBrains_Mono'] text-xs text-[#737685] uppercase tracking-wider">
                    <span>{article.date}</span>
                    <span className="w-1 h-1 bg-[#c3c6d6] rounded-full" />
                    <span>{article.readTime}</span>
                  </div>
                </div>
              </article>
            ))}
          </section>

          {/* Sidebar */}
          <aside className="lg:col-span-4 space-y-12">
            {/* Categories */}
            <div>
              <h3 className="text-xl font-bold text-[#131b2e] mb-6 flex items-center gap-2">
                <span className="w-1.5 h-6 bg-[#003594] rounded-full" />
                Categories
              </h3>
              <nav className="space-y-1">
                {categories.map((category) => (
                  <button
                    key={category}
                    type="button"
                    onClick={() => setActiveCategory(category)}
                    className={`w-full flex items-center justify-between px-4 py-3 rounded-xl text-left transition-all duration-200 ${
                      activeCategory === category
                        ? 'bg-[#e1e7ff] text-[#003594] font-bold'
                        : 'text-[#434654] hover:bg-white hover:text-[#003594]'
                    }`}
                  >
                    <span>{category}</span>
                    {activeCategory === category && (
                      <ChevronRight className="w-4 h-4 opacity-60" />
                    )}
                  </button>
                ))}
              </nav>
            </div>

            {/* Popular Posts */}
            <div>
              <h3 className="text-xl font-bold text-[#131b2e] mb-6 flex items-center gap-2">
                <span className="w-1.5 h-6 bg-[#006c49] rounded-full" />
                Popular Posts
              </h3>
              <div className="space-y-6">
                {popularPosts.map((post) => (
                  <div key={post.id} className="flex gap-4 group cursor-pointer items-start">
                    <div className="w-14 h-14 flex-shrink-0 overflow-hidden rounded-2xl bg-[#eaedff]">
                      <img
                        src={post.image}
                        alt={post.title}
                        className="w-full h-full object-cover"
                      />
                    </div>
                    <div className="flex-1 min-w-0">
                      <h4 className="text-sm font-bold text-[#131b2e] leading-tight group-hover:text-[#003594] transition-colors line-clamp-2">
                        {post.title}
                      </h4>
                      <span className="text-[11px] text-[#737685] font-medium mt-1 block uppercase tracking-tight">
                        {post.date}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Newsletter Subscription Card */}
            <div className="p-8 rounded-2xl bg-[#004ac6] relative overflow-hidden group">
              <div className="absolute top-0 right-0 w-32 h-32 bg-white/10 rounded-full -mr-16 -mt-16 transition-transform duration-500 group-hover:scale-125" />
              <h3 className="text-xl font-bold text-white mb-3 relative z-10">
                Get the best of tech directly in your inbox.
              </h3>
              <p className="text-[#dbe1ff] text-sm mb-6 relative z-10">
                No spam, just pure insights once a week.
              </p>
              <form
                onSubmit={(e) => e.preventDefault()}
                className="space-y-3 relative z-10"
              >
                <input
                  type="email"
                  required
                  placeholder="Your email address"
                  className="w-full px-4 py-3 bg-white/10 border border-white/20 rounded-xl text-white placeholder:text-white/50 focus:bg-white/20 focus:outline-none transition-all"
                />
                <button
                  type="submit"
                  className="w-full py-3 bg-white text-[#003594] font-bold rounded-xl hover:bg-[#9df4c8] transition-colors"
                >
                  Subscribe Now
                </button>
              </form>
            </div>
          </aside>
        </div>

        {/* Pagination */}
        <div className="mt-16 flex items-center justify-center gap-2">
          {[1, 2, 3].map((page) => (
            <button
              key={page}
              type="button"
              className="w-10 h-10 flex items-center justify-center rounded-xl bg-white border border-[#c3c6d6]/30 text-[#131b2e] hover:bg-[#003594] hover:text-white transition-all"
            >
              {page}
            </button>
          ))}
          <span className="mx-2 text-[#737685]">...</span>
          <button
            type="button"
            aria-label="Next page"
            className="w-10 h-10 flex items-center justify-center rounded-xl bg-white border border-[#c3c6d6]/30 text-[#131b2e] hover:bg-[#003594] hover:text-white transition-all"
          >
            <ChevronRight className="w-4 h-4" strokeWidth={2.5} />
          </button>
        </div>
      </div>
    </main>
  );
}

export default Blog;