import { useRef, useState } from 'react';
import { ArrowRight, ChevronLeft, ChevronRight } from 'lucide-react';

// NOTE: Project images below are temporary placeholder URLs generated by the
// Stitch design tool (googleusercontent.com). Swap these for your own project
// screenshots in src/assets when ready.
const projects = [
  {
    id: 'analytics',
    title: 'Predictive Analytics Suite',
    tag: 'DATA ENGINE',
    accent: 'primary',
    description:
      'AI-driven foresight that transforms raw data into strategic market dominance.',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDp1gWsRFnZEyzazm_ELBnf3xwn6P0le468YFFPpwFRlcnvAbEhjWqooZbiegRntNCNYfSeiID5ZSKXrhz1s2zQsR1YPpdUw4WLnYZg7QiEbypg4A8c3Uxz2KSTUncX2zyZLd19i31YvCFLulM4jneOAgAlHdzotlCeeLSenBAlsJppI09W-pPLz-iuMFbpAMJbYKAkhyYTf5UBr0Kp8y3bKppKm3wy8aL6a6id_LvvV5o6au0p0otPmA',
  },
  {
    id: 'blockchain',
    title: 'Quantum Asset Network',
    tag: 'BLOCKCHAIN',
    accent: 'secondary',
    description:
      'Ultra-secure, distributed ledger technology powering the future of digital finance.',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuC5ecSLfbQnr9EIl0fqr4barlUlSsKiTjbQ_1P3m47SzHMD-szuitfAci27-jpkm6BnGlLwpcOalNjX1nCJCxFJ9TVSU34bDts1sKb2eBvNFbHXMa86ACuQmxmT4lQcs0GV6uhDaH_aQz0LTKvO3oExZ8mGI2OLpzsPU_LRfPO-0qDrbCjpKMSfBuCuQaSf0ncrloJUbd0dXQl9Z8dSTof8V75qEfn5Ve9f7j4r2yG5tM5r6Ag4hwX_Ow',
  },
  {
    id: 'zenith',
    title: 'Zenith Productivity Portal',
    tag: 'ECOSYSTEM',
    accent: 'primary',
    description:
      'Unified workspace harmonizing team coordination and individual flow states.',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDaE3fLJfTk7JhIDzW1jyRrLgnx9p3rti4bk8OGTI1Zj4mlK2AZa5bUZZqnD0ZIRWmuaf3x9qbcSRpE1HSlyDB36Lw2g9b-LvOIAYhNw9pZZClYr7eraWlIYwI5qAvDPhh__VoDYq6pjqQ1o7dgii-s1hmZOvuFjhnwS4v1FGwjIx0mLNPn0161vxuEJeffWh3VyR7KH1_X8nL65K54ezJd_iKyiOonG70rA_z7FfurPLLG1oQpNHM6JA',
  },
  {
    id: 'velocity',
    title: 'Velocity CRM Enterprise',
    tag: 'ENTERPRISE',
    accent: 'secondary',
    description:
      'Full-stack customer relationship engine designed for hyper-growth scaling.',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuA6BX5BtCO4q2vRj8JBrZXj0o36kt1kZYYb1t2-t4vOvc_HIAebQalBFlaAmgtCfUx-P3IelvBudSr3Tf3PM9M8Csabk0Ow6u5b1KQNtv0mSoRI-uDxfZr2g8xnjxUeNvLXOJ3-FWtZHLZGWgFHnT3BVPkdNSmaEiyitF3DTso_7nXF6ANOYmjCg2s97CTMA8dnShpVjE1UHBk56J2r0oO7ZnQLqKwHdgKjTnZoRGfkgw8Z57io6HYVKg',
  },
  {
    id: 'app-dev',
    title: 'App Development',
    tag: 'MOBILE',
    accent: 'primary',
    description:
      'High-performance mobile solutions built for seamless user experiences across all platforms.',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDsksX20hC35kG_wzINinIj1qtPpiYtKT-ztIVCwfoy58uo8yF7cGwIDlNy4jwBRMWQYYhmgXI5W99Y3qzS9td1ATK-eSq_gJbyKkGmFyBcs5yIhDY_QZhBwjlqOo4eAWX7jCfzpby-BPJsiPPWzSC7Ma85dsfH0ZcEylK4jlZG5ljcwwwHjn_Ih920AjKcp7t1IxhzZ5zmjoj9CjUbCbe6qvB9cZvS7YK0vvKQaNOZZWgdaCxtb4JtPg',
  },
  {
    id: 'crm-system',
    title: 'CRM System',
    tag: 'MANAGEMENT',
    accent: 'secondary',
    description:
      'Intelligent customer management platforms that drive retention and lifetime value.',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCXjWmi09aM6JoshdaR7qj3HosxbbPML_cUT2ADveaF_cfMhYf0TSAaC9GTt-8KbJPrVOTQM3RE6PxuHVFKIiEWps3l5STOq83EzR6_NCc5PBPbjOWtfpiNJASBaWbj6eFLagESLgA3Zh8xbn_E2sXPXxARcosuuWwXdXwinLNXXI_8Hcu09cKYCJdT6BXARIS2t9mG2qRVSyQNZUN04M0fBvRqw2HBJoKvd6BtnKA1km_evE9W_Zt9sA',
  },
  {
    id: 'hubspot',
    title: 'HubSpot Integration',
    tag: 'AUTOMATION',
    accent: 'primary',
    description:
      'Advanced marketing automation workflows that synchronize sales and marketing efforts.',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCWMf3af3LSaOB6fUN-mgBeQXXsKdNAhHZM-Q8xoyla_LlfnJUxJByu_jkpD3kZW_-6I4KBi5ZGkWZmjQQuLNM4CFkut_HxvavIEL9a47Hc-8tc9US2SIJxGz5w-7XW87-IBpvltpTWDlu_V4hRt6thDp7chv0MQyuMgys-QyBr-Ambul6LRhdlS5TUv2qV8yYXKeiK6OEoFsvk2_qgAFTRLxaayrQZS-AmTtIaILmhweCQBwbmVx_5Lw',
  },
];

const accentColors = {
  primary: { bg: 'rgba(0,74,198,0.2)', border: 'rgba(0,74,198,0.3)' },
  secondary: { bg: 'rgba(0,108,73,0.2)', border: 'rgba(0,108,73,0.3)' },
};

function ProjectCard({ project }) {
  const colors = accentColors[project.accent];
  return (
    <div
      className="flex-none w-[200px] md:w-[300px] snap-start bg-white border border-[#c3c6d7] rounded-t-[24px] rounded-b-xl overflow-hidden group/card cursor-pointer shadow-md hover:shadow-xl transition-all duration-500"
      data-purpose="project-card"
    >
      <div className="relative h-[120px] md:h-[150px] overflow-hidden">
        <img
          alt={project.title}
          className="w-full h-full object-cover group-hover/card:scale-110 transition-transform duration-1000 ease-out"
          src={project.image}
        />
        <div className="absolute inset-0 bg-black/40 group-hover/card:bg-black/10 transition-colors duration-500" />
        <div className="absolute top-2.5 left-2.5">
          <span
            style={{ backgroundColor: colors.bg, borderColor: colors.border }}
            className="backdrop-blur-md border text-white text-[7px] font-bold px-2 py-0.5 rounded-full uppercase tracking-[0.1em]"
          >
            {project.tag}
          </span>
        </div>
      </div>
      <div className="p-3 md:p-4">
        <h3 className="font-['Hanken_Grotesk'] text-sm md:text-base font-bold mb-1.5 md:mb-2 transition-colors tracking-tight text-[#131b2e] group-hover/card:text-[#006c49]">
          {project.title}
        </h3>
        <p className="text-[#434655] text-xs md:text-sm leading-relaxed mb-3 md:mb-4 line-clamp-2">
          {project.description}
        </p>
        <div className="flex items-center gap-1.5 font-bold text-[10px] uppercase tracking-widest group-hover/card:gap-3 transition-all text-[#006c49]">
          <span>Explore Case Study</span>
          <ArrowRight className="w-3.5 h-3.5" strokeWidth={2.5} />
        </div>
      </div>
    </div>
  );
}

export default function FeaturedProjects() {
  const scrollerRef = useRef(null);
  const [activeIndex, setActiveIndex] = useState(0);

  const scrollByAmount = (direction) => {
    const el = scrollerRef.current;
    if (!el) return;
    el.scrollBy({ left: direction * el.clientWidth * 0.85, behavior: 'smooth' });
  };

  const scrollToIndex = (index) => {
    const el = scrollerRef.current;
    if (!el) return;
    const card = el.children[index];
    if (card) {
      card.scrollIntoView({ behavior: 'smooth', inline: 'start', block: 'nearest' });
      setActiveIndex(index);
    }
  };

  return (
    <section
      className="pt-6 pb-12 md:pt-8 md:pb-16 px-6 md:px-12 max-w-[1440px] mx-auto overflow-hidden"
      data-purpose="portfolio-showcase"
      id="featured-projects"
    >
      {/* Section Header */}
      <div className="mb-6 md:mb-8 ml-2 lg:ml-4">
        <div className="flex items-center gap-4 mb-6">
          <div className="h-[1px] w-16 bg-[#004ac6]" />
          <span className="font-['Hanken_Grotesk'] text-[#004ac6] font-semibold text-sm tracking-[0.4em] uppercase">
            OUR WORK
          </span>
        </div>
        <h2 className="font-['Hanken_Grotesk'] text-2xl md:text-5xl font-semibold leading-tight tracking-tight text-[#131b2e]">
          Featured <span className="text-[#004ac6]">Projects</span>
        </h2>
      </div>

      {/* Carousel */}
      <div className="relative group" data-purpose="carousel-wrapper">
        {/* Navigation Buttons */}
        <div className="absolute inset-y-0 -left-2 md:-left-12 flex items-center z-20 pointer-events-none">
          <button
            type="button"
            aria-label="Previous project"
            onClick={() => scrollByAmount(-1)}
            className="pointer-events-auto w-12 h-12 md:w-14 md:h-14 bg-white backdrop-blur-xl rounded-full border border-[#c3c6d7] flex items-center justify-center hover:bg-[#eaedff] transition-all shadow-lg"
          >
            <ChevronLeft className="w-6 h-6 text-[#131b2e]" />
          </button>
        </div>
        <div className="absolute inset-y-0 -right-2 md:-right-12 flex items-center z-20 pointer-events-none">
          <button
            type="button"
            aria-label="Next project"
            onClick={() => scrollByAmount(1)}
            className="pointer-events-auto w-12 h-12 md:w-14 md:h-14 bg-white backdrop-blur-xl rounded-full border border-[#c3c6d7] flex items-center justify-center hover:bg-[#eaedff] transition-all shadow-lg"
          >
            <ChevronRight className="w-6 h-6 text-[#131b2e]" />
          </button>
        </div>

        {/* Carousel Track */}
        <div
          ref={scrollerRef}
          className="flex flex-nowrap gap-6 md:gap-8 overflow-x-auto pb-8 pt-4 no-scrollbar snap-x px-2 lg:px-4"
        >
          {projects.map((project) => (
            <ProjectCard key={project.id} project={project} />
          ))}
        </div>

        {/* Pagination Dots */}
        <div className="flex justify-center items-center gap-2.5 mt-4" data-purpose="carousel-dots">
          {projects.map((project, index) => (
            <button
              key={project.id}
              type="button"
              aria-label={`Go to ${project.title}`}
              onClick={() => scrollToIndex(index)}
              className={`rounded-full transition-all duration-300 ${
                index === activeIndex
                  ? 'w-3 h-3 bg-[#004ac6]'
                  : 'w-2 h-2 bg-[#c3c6d7] hover:bg-[#737686]'
              }`}
            />
          ))}
        </div>
      </div>
    </section>
  );
}