import { useRef } from 'react';
import {
  ArrowRight,
  ChevronLeft,
  ChevronRight,
  Cloud,
  Sparkles,
  ShieldCheck,
  Code2,
  Smartphone,
  Zap,
} from 'lucide-react';

// NOTE: Card images below are temporary placeholder URLs generated by the
// Stitch design tool (googleusercontent.com). These can expire or change —
// swap them out for your own hosted images in src/assets when ready.
const services = [
  {
    id: 'cloud',
    icon: Cloud,
    title: 'Cloud Infrastructure',
    tag: 'Enterprise Solutions',
    description:
      'Highly scalable and secure cloud architectures designed for zero downtime.',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCoF2C18LnMzX-tlaChBv39A455VofW3MsIegfDXj-Rft2pFGs_7P37439vtDh_47RxhGsVA3CPO1A5r6m82GbvdAvR8E7MoIzRESf1S5VvPwKfUA6Us0ZszpcBu2yYTmtQXln2nxmF9fncYctCfmp39Xfn8G7emlStN4NdkFB2A_oDCp6RZXIjYGTFp_CmIcVrglpBT3Bxre_sxp9ptrAJqkgEpKHAR6wdgEf1tE4Lq2PBHr_FMmms6g',
    stats: [
      { label: 'Uptime', value: '99.9%', highlight: '#6ffbbe' },
      { label: 'Scale', value: 'Auto' },
      { label: 'Rating', value: '4.9' },
    ],
  },
  {
    id: 'ai',
    icon: Sparkles,
    title: 'AI & Intelligence',
    tag: 'Data Science',
    description:
      'Machine learning to automate complex processes and extract insights.',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAL29QJTHkHDyAGK9Vi80_FO7HkKzIqSH0Im_5zsZpZ4CZAQ_NU3NU8fFBEP-v1U0f5hY22D-FRDu2ETVnATTO_ef1KYfRyAlkNLyowHBzXuFq3yjBgOMfyb35_ln43z6CwI9atg5Wsj2XFNZAfWGtd1vTMN7Hyl-c-X_46VSTMh10DuMgLJhVnh0H6nTNzAFKGdmBAQnqPoQi6FP_tAbCpNtXz8r-7Yx97V_ufeT8ucG2klTAgvPgTBQ',
    stats: [
      { label: 'Efficiency', value: '+40%', highlight: '#6ffbbe' },
      { label: 'Model', value: 'LLM' },
      { label: 'Rating', value: '5.0' },
    ],
  },
  {
    id: 'cyber',
    icon: ShieldCheck,
    title: 'Cyber Security',
    tag: 'Defense Monitoring',
    description:
      'Comprehensive protection using advanced threat detection systems.',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCiu1hVd6rdfdaf9A3y9FJM9dm8LmXC79SbkXAcNdfPXxb73EaLhBXAH5ARm1yx8LOiS1EyiS6oCV68ie2oG7G3Hhigli4mT1d1mgNGZz4ofPpg3WycvG0KXFlrAN9a0QKo1GSfH2vMb6dQ2Nn6WsUjzA5DdUtXsJSaMkDcfUNAh5lAvqa1SAV_gPtIupZ8xYXFCKpXEEjZx5MHzpmhoOPrcz3GK_nJt5iM2dyw6jbvKOukwPws9PnOtg',
    stats: [
      { label: 'Response', value: '<5m', highlight: '#f87171' },
      { label: 'Threats', value: 'Zero' },
      { label: 'Rating', value: '4.8' },
    ],
  },
  {
    id: 'web',
    icon: Code2,
    title: 'Full Stack Dev',
    tag: 'React, Node.js',
    description:
      'High-performance web apps with cutting-edge frameworks.',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuA5pft13mvdL61p0-mQm-H6kWMFC6gTkMeScOccX3Vg1Id0QuGuvvRDjpsgznZi9aW9znmvug68hmYWaMVgUfycLXmFSeJCa187xz70Rw4KWAH7L_popyvCUp4T5UkYOkBqm1kw-O9S_H_EghRqvzKiAjynoxmC_YZtoZrkLw3D2f_lNYk1F4vVUo-K3SVOghk2hiHDBiMVPWWPU8Bp1OLlOs4Dg0etL9xwDJZe4w6rHBX0wm8CyuIHTA',
    stats: [
      { label: 'Speed', value: '98/100', highlight: '#6ffbbe' },
      { label: 'Stack', value: 'MERN' },
      { label: 'Rating', value: '4.9' },
    ],
  },
  {
    id: 'app',
    icon: Smartphone,
    title: 'App Development',
    tag: 'Custom Solutions',
    description:
      'High-performance mobile and web applications built with cutting-edge tech stacks.',
    image:
      'https://lh3.googleusercontent.com/aida/AP1WRLs-OuqkCXbW8_XpsX_ZQEALDL0tf-X8ShUUGuFih5f9TlAzs5Lna4SVUrbB2wEQeSZnQRJJMGj9COEUWux6_XU1F2r0GHKPRGe0k2-3UsEeWv9nCpGprtJY_2hI_4_GwnpNdZwjDsjW21OIm3524uWlFjUweXs435MwQ36Hjdc1BQMAIw1zh4vY2aYB_WKRn9LaNNMRCUsLBTORu1_YWYjniH7l21X1dpA7tekzLNLQtdkj20t_ZEbDgUB9',
    stats: [
      { label: 'Uptime', value: '99.9%', highlight: '#6ffbbe' },
      { label: 'Scale', value: 'Auto' },
      { label: 'Rating', value: '4.9' },
    ],
  },
  {
    id: 'crm',
    icon: Zap,
    title: 'CRM & Automation',
    tag: 'Efficiency First',
    description:
      'Streamline your workflows and boost sales with intelligent CRM systems and custom automation.',
    image:
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
    stats: [
      { label: 'Efficiency', value: '+40%', highlight: '#6ffbbe' },
      { label: 'Model', value: 'Custom' },
      { label: 'ROI', value: '3.5x' },
    ],
  },
];

function ServiceCard({ service }) {
  const Icon = service.icon;
  return (
    <article
      className="flex-none w-[220px] md:w-[260px] snap-center"
      data-purpose={`service-card-${service.id}`}
    >
      <div className="relative h-[360px] rounded-3xl overflow-hidden bg-[#131b2e] shadow-xl service-card group">
        <img
          alt={service.title}
          className="absolute inset-0 w-full h-full object-cover opacity-70 group-hover:scale-105 transition-transform duration-700"
          src={service.image}
        />
        <div className="absolute inset-0 card-gradient-overlay flex flex-col justify-end p-4 text-white">
          <div className="mb-auto">
            <div className="bg-white/10 backdrop-blur-md w-8 h-8 flex items-center justify-center rounded-xl">
              <Icon className="h-4 w-4" />
            </div>
          </div>

          <div>
            <h3 className="font-['Hanken_Grotesk'] text-lg font-semibold mb-1">{service.title}</h3>
            <div className="flex items-center gap-2 text-white/60 text-xs mb-2">
              <span>{service.tag}</span>
            </div>
            <p className="text-white/80 text-sm leading-relaxed mb-4 line-clamp-2">
              {service.description}
            </p>
            <div className="grid grid-cols-3 gap-2 border-t border-white/10 pt-3">
              {service.stats.map((stat) => (
                <div key={stat.label}>
                  <span className="font-['JetBrains_Mono'] block text-[9px] font-medium uppercase tracking-wider text-white/40 mb-0.5">
                    {stat.label}
                  </span>
                  <span
                    className="text-sm font-bold"
                    style={stat.highlight ? { color: stat.highlight } : undefined}
                  >
                    {stat.value}
                  </span>
                </div>
              ))}
            </div>
          </div>

          <div className="absolute bottom-4 right-4">
            <button
              type="button"
              aria-label={`Learn more about ${service.title}`}
              className="bg-white text-[#131b2e] w-8 h-8 rounded-full flex items-center justify-center shadow-lg hover:bg-[#004ac6] hover:text-white transition-colors"
            >
              <ArrowRight className="h-4 w-4" />
            </button>
          </div>
        </div>
      </div>
    </article>
  );
}

export default function Services() {
  const scrollerRef = useRef(null);

  return (
    <section className="relative pt-8 pb-4 overflow-hidden bg-[#faf8ff]">
      {/* Section Header */}
      <div className="max-w-7xl mx-auto px-6 mb-10">
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-12">
          {/* Left: Label + Heading */}
          <div className="lg:w-1/3">
            <span className="font-['JetBrains_Mono'] text-[11px] font-bold tracking-[0.15em] text-[#004ac6] uppercase mb-4 block">
              WHAT WE DO
            </span>
            <h2 className="font-['Hanken_Grotesk'] text-4xl lg:text-5xl font-extrabold text-[#131b2e] leading-[1.1] tracking-tight">
              End-to-End Digital Solutions <br /> Tailored for{' '}
              <span className="bg-clip-text text-transparent bg-gradient-to-r from-[#4edea3] to-[#2563eb] font-extrabold">
                Your Business
              </span>
            </h2>
          </div>

          {/* Middle: Description */}
          <div className="lg:w-2/5">
            <p className="text-base text-[#434655] leading-relaxed">
              From product strategy to development and growth, we deliver
              digital solutions that drive real results in a changing
              technical landscape. We build for performance, security, and
              scalability.
            </p>
          </div>

          {/* Right: Action Button */}
          <div className="flex-shrink-0">
            <button
              type="button"
              className="group flex items-center gap-2 border border-[#c3c6d7] px-6 py-3 rounded-xl hover:bg-[#eaedff] transition-all font-semibold text-[#131b2e]"
            >
              View All Services
              <ArrowRight className="h-5 w-5 group-hover:translate-x-1 transition-transform" />
            </button>
          </div>
        </div>
      </div>

      {/* Immersive Carousel */}
      <div className="relative">
        <div
          ref={scrollerRef}
          className="flex overflow-x-auto no-scrollbar snap-x snap-mandatory px-[5vw] gap-6 pb-12"
        >
          {services.map((service) => (
            <ServiceCard key={service.id} service={service} />
          ))}
        </div>

        {/* Navigation Arrows */}
        <button
          type="button"
          aria-label="Scroll left"
          onClick={() => scrollerRef.current?.scrollBy({ left: -280, behavior: 'smooth' })}
          className="absolute top-1/2 -translate-y-1/2 left-4 z-10 hidden md:flex bg-white/90 backdrop-blur p-3 rounded-full shadow-lg border border-[#c3c6d7] text-[#434655] hover:text-[#004ac6] transition-colors"
        >
          <ChevronLeft className="h-5 w-5" />
        </button>
        <button
          type="button"
          aria-label="Scroll right"
          onClick={() => scrollerRef.current?.scrollBy({ left: 280, behavior: 'smooth' })}
          className="absolute top-1/2 -translate-y-1/2 right-4 z-10 hidden md:flex bg-white/90 backdrop-blur p-3 rounded-full shadow-lg border border-[#c3c6d7] text-[#004ac6] transition-colors"
        >
          <ChevronRight className="h-5 w-5" />
        </button>
      </div>
    </section>
  );
}